name: pay_bridge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  bottom_bar: ^2.0.3
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.3
  #to save qr code in file 
  path_provider: ^2.1.5
  #to generate qr code 
  qr_flutter: ^4.1.0
  # to show qr code 
  flutter_svg: ^2.2.0
  #to scan qr code
  qr_code_scanner_plus: ^2.0.10+1
  animated_custom_dropdown: 3.1.1
  searchfield: ^1.3.2

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/PayBridgeLogo.png"
  min_sdk_android: 21 # android min 

flutter:
  uses-material-design: true
  
  assets:
    - images/
